const theme={ 
    light:{
        theme:"light",
        headercolor:"#FF7D54",
        titlecolor:"#09090c",
        timecolor:"#4d4344",
        iconcolor:"#09090c",
        textcolor:"#09090c",
        foreground:"#09090c",
        imagebordercolor:"#D3D3D3",
        background:"#fff",
        secondarybg:"#d0e0fd",
        inputbg:"#f2f2f2",
        placeholderTextColor:"#555",
    },
    dark:{
        theme:"dark",
        headercolor:"#FF7D54",
        titlecolor:"#09090c",
        timecolor:"#4d4344",
        foreground:"#09090c",
        imagebordercolor:"#555",
        textcolor:"#fff",
        iconcolor:"#fff",
        background:"#09090c",
        secondarybg:"#d0e0fd",
        inputbg:"#28282B",
        placeholderTextColor:"#f5f5f5",
    }
}
export default theme